service: file-upload

frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  profile: 'lambda-dev-recluta'
  region: 'us-east-1'

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler::handleRequest
    events:
      - http:
          path: status
          method: get

plugins:
  - serverless-offline